const $ = id => document.getElementById(id);
const text = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const date = value => value ? new Intl.DateTimeFormat('zh-CN', { year: 'numeric', month: 'short', day: 'numeric' }).format(new Date(value)) : '—';

export function renderJobs(state) { $('result-count').textContent = `${state.total} 个职位`; $('loading-copy').textContent = state.jobs.length < state.total ? `已加载 ${state.jobs.length} 个` : ''; $('jobs-body').innerHTML = state.jobs.map(job => `<tr data-job-id="${job.id}"><td class="check-col"><input class="applied-toggle" type="checkbox" data-job-id="${job.id}" ${job.applied ? 'checked' : ''} aria-label="标记 ${text(job.title)} 为已申请" /></td><td class="role"><a href="${text(job.url)}" target="_blank" rel="noreferrer">${text(job.title)}</a>${job.team ? `<small>${text(job.team)}</small>` : ''}</td><td>${text(job.company)}</td><td class="location">${text(job.location || '—')}</td><td class="date">${date(job.discovered_at)}</td><td><span class="source">${text(job.source)}</span></td><td><a class="external-link" href="${text(job.url)}" target="_blank" rel="noreferrer" aria-label="打开职位">↗</a></td></tr>`).join(''); $('empty-state').classList.toggle('hidden', state.jobs.length !== 0); $('load-more').classList.toggle('hidden', !state.nextCursor); }
export function renderRuns(runs) { const history = runs.filter(run => run.status !== 'running'); $('runs-list').innerHTML = history.length ? history.map(run => `<button class="run-row" data-run-id="${run.id}"><span class="run-date">${date(run.started_at)}</span><span class="run-main"><strong>Run #${run.id}</strong><small>${run.companies_succeeded}/${run.companies_total} 家公司 · ${run.jobs_saved} 个新职位</small></span><span class="status-badge ${text(run.status)}">${text(run.status)}</span></button>`).join('') : '<div class="run-empty">还没有数据库运行记录。</div>'; }
export function renderLatestRun(runs) { const run = runs.find(item => item.jobs_saved > 0) || runs[0]; if (!run) { $('latest-run-title').textContent = '还没有运行记录'; $('latest-run-detail').textContent = '在「运行与日志」中启动首次搜索。'; $('open-latest-run').classList.add('hidden'); return; } $('latest-run-title').textContent = `${date(run.started_at)} · Run #${run.id}`; $('latest-run-detail').textContent = `${run.companies_succeeded}/${run.companies_total} 家公司 · ${run.jobs_saved} 个新职位`; $('open-latest-run').dataset.runId = run.id; $('open-latest-run').classList.remove('hidden'); }
export function renderActiveRun(run) { $('active-run').classList.remove('hidden'); const percent = run.total ? Math.round(run.progress / run.total * 100) : 0; $('run-progress').style.width = `${percent}%`; $('run-progress-percent').textContent = `${percent}%`; $('run-progress-copy').textContent = run.status === 'completed' ? '搜索完成，职位已保存。' : run.status === 'failed' ? '搜索失败，请查看日志。' : `${run.company || '准备中'} · ${run.progress}/${run.total || '—'} 家公司`; $('active-run-title').textContent = run.status === 'completed' ? '本次搜索已完成' : run.status === 'failed' ? '本次搜索失败' : '正在获取职位…'; const badge = $('run-status'); badge.textContent = run.status.toUpperCase(); badge.className = `status-badge ${run.status}`; $('run-logs').innerHTML = (run.logs || []).map(log => `<div><time>${text(log.time)}</time><span>${text(log.message)}</span></div>`).join(''); $('run-logs').scrollTop = $('run-logs').scrollHeight; const complete = $('run-complete-actions'); complete.classList.toggle('hidden', run.status !== 'completed' || !run.summary?.run_id); if (run.summary?.run_id) $('view-current-run').dataset.runId = run.summary.run_id; }
export function setProfiles(profiles) { $('run-profile').innerHTML = profiles.map(profile => `<option value="${text(profile)}">${text(profile)}</option>`).join(''); }
export function setTab(tab) { document.querySelectorAll('.nav-item').forEach(button => button.classList.toggle('active', button.dataset.tab === tab)); document.querySelectorAll('.tab-panel').forEach(panel => panel.classList.toggle('active', panel.id === `${tab}-tab`)); }
export function toast(message, type = '') { const item = $('toast'); item.textContent = message; item.className = `toast ${type}`; setTimeout(() => item.classList.add('hidden'), 3200); }
